README.md, docs/architecture.md
- Distinguished time series evaluation from outlier classification
evaluation. (Former uses RMSE or similar; latter uses precision/recall
or similar.)
- Clarified success criteria for an automated model selection algorithm.
=> Extended the architecture documentation

pom.xml, tools/pom.xml, tools/src/main/java/com/expedia/adaptivealerting/tools/kafka/KafkaMetricSubscriber.java, tools/src/main/java/com/expedia/adaptivealerting/tools/kafka/KafkaWhiteNoiseMetricSource.java, tools/src/main/java/com/expedia/adaptivealerting/tools/metricsource/AbstractMetricSource.java, tools/src/main/java/com/expedia/adaptivealerting/tools/metricsource/ConsoleLogMetricSubscriber.java, tools/src/main/java/com/expedia/adaptivealerting/tools/metricsource/MetricSource.java, tools/src/main/java/com/expedia/adaptivealerting/tools/metricsource/MetricSubscriber.java, tools/src/main/java/com/expedia/adaptivealerting/tools/metricsource/WhiteNoiseMetricSource.java, tools/src/test/java/com/expedia/adaptivealerting/tools/metricsource/ConsoleLogMetricSubscriberTest.java, tools/src/test/java/com/expedia/adaptivealerting/tools/metricsource/WhiteNoiseMetricSourceTest.java
This will be for things like fake data sources, visualization tools and
so forth.
=> Moved model development tools into their own Maven module.

docs/custom-anom-models.md
=> update anom detector sections

kafka/src/main/java/com/expedia/adaptivealerting/kafka/serde/HaystackMetricTimeStampExtractor.java, kafka/src/main/resources/config/base.conf
adding this as com.expedia.www.haystack.commons.kstreams.MetricPointTimestampExtractor doesn't handle the case when record fail to deserialise
=> adding HaystackMetricTimestampExtractor

kafka/pom.xml, pom.xml
1 - simplifying the version definitions, removing duplicate ones
2 -  added build.helper.plugin to define additional test sources for kafka module
=> Cleaning up maven dependencies

anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/ConstantThresholdAnomalyDetector.java, anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/CusumAnomalyDetector.java, anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/EwmaAnomalyDetector.java, anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/PewmaAnomalyDetector.java, anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/randomcutforest/RandomCutForestAnomalyDetector.java, anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/randomcutforest/Shingle.java, anomdetect/src/test/java/com/expedia/adaptivealerting/anomdetect/ConstantThresholdAnomalyDetectorTest.java, anomdetect/src/test/java/com/expedia/adaptivealerting/anomdetect/CusumAnomalyDetectorTest.java, anomdetect/src/test/java/com/expedia/adaptivealerting/anomdetect/EwmaAnomalyDetectorTest.java, anomdetect/src/test/java/com/expedia/adaptivealerting/anomdetect/PewmaAnomalyDetectorTest.java, anomdetect/src/test/java/com/expedia/adaptivealerting/anomdetect/randomcutforest/MetricPointQueueTest.java, core/src/main/java/com/expedia/adaptivealerting/core/util/MetricUtil.java, core/src/test/java/com/expedia/adaptivealerting/core/util/MetricPointUtilTest.java, kafka/src/main/resources/config/base.conf, kafka/src/test/scala/com/expedia/adaptivealerting/pipeline/integration/test/ConstantThresholdBasedE2ETestSpec.scala, tools/src/main/java/com/expedia/adaptivealerting/tools/pipeline/source/MetricFrameMetricSource.java, tools/src/main/java/com/expedia/adaptivealerting/tools/pipeline/source/RandomWalkMetricSource.java, tools/src/main/java/com/expedia/adaptivealerting/tools/pipeline/source/WhiteNoiseMetricSource.java
Random Cut Forest hooked with Kafka
=> Random Cut Forest hooked with Kafka

anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/randomcutforest/RandomCutForestAnomalyDetector.java
Fixing the missing metric in anomaly result for RCF
=> Fixing the missing metric in anomaly result for RCF

modelservice/docker/Dockerfile, modelservice/docker/jmxtrans-agent.xml, modelservice/docker/start-app.sh
This PR retains the name **haystack-adaptive-alerting-modelservice** for docker image
but builds the image using new artifactId **adaptive-alerting-modelservice**
=> changing scripts for new artifact name adaptive-alerting-modelservice

anomdetect/pom.xml, anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/AnomalyDetectorMapper.java, anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/util/ModelServiceConnector.java, anomdetect/src/test/java/com/expedia/adaptivealerting/anomdetect/AnomalyDetectorMapperTest.java, kafka/src/main/java/com/expedia/adaptivealerting/kafka/mapper/KafkaAnomalyDetectorMapper.java, kafka/src/test/scala/com/expedia/adaptivealerting/pipeline/integration/test/ConstantThresholdBasedE2ETestSpec.scala, pom.xml
This depends on a ModelServiceConnector, which isn't implemented yet. I'll
follow up with that in a subsequent PR.
=> Implemented AnomalyDetectorMapper.

anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/AnomalyDetectorManager.java, anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/aquila/AquilaAnomalyDetector.java, anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/aquila/AquilaAnomalyDetectorFactory.java, core/pom.xml, core/src/main/java/com/expedia/adaptivealerting/core/data/MetricFrame.java, core/src/main/java/com/expedia/adaptivealerting/core/data/io/MetricFrameLoader.java, kafka/src/main/java/com/expedia/adaptivealerting/kafka/detector/KafkaAnomalyDetectorManager.java, kafka/src/main/java/com/expedia/adaptivealerting/kafka/mapper/KafkaAnomalyDetectorMapper.java, kafka/src/main/java/com/expedia/adaptivealerting/kafka/serde/JsonPojoDeserializer.java, kafka/src/main/java/com/expedia/adaptivealerting/kafka/serde/JsonPojoSerializer.java, kafka/src/main/java/com/expedia/adaptivealerting/kafka/serde/MetricDataSerde.java, kafka/src/main/resources/config/base.conf, pom.xml, tools/pom.xml, tools/src/main/java/com/expedia/adaptivealerting/tools/kafka/KafkaMetricDataForwarder.java, tools/src/main/java/com/expedia/adaptivealerting/tools/pipeline/source/AbstractMetricSource.java, tools/src/main/java/com/expedia/adaptivealerting/tools/pipeline/source/MetricFrameMetricSource.java, tools/src/main/java/com/expedia/adaptivealerting/tools/pipeline/source/MetricSource.java, tools/src/main/java/com/expedia/adaptivealerting/tools/pipeline/source/RandomWalkMetricSource.java, tools/src/main/java/com/expedia/adaptivealerting/tools/pipeline/source/WhiteNoiseMetricSource.java
Also updated KafkaMetricDataForwarder to support command line use.
=> Connected Aquila virtual detector to Aquila detector

modelservice/src/main/java/com/expedia/adaptivealerting/modelservice/entity/Detector.java, modelservice/src/main/java/com/expedia/adaptivealerting/modelservice/entity/MetricDetectorMapping.java, modelservice/src/main/java/com/expedia/adaptivealerting/modelservice/entity/Model.java, modelservice/src/main/java/com/expedia/adaptivealerting/modelservice/entity/projection/InlineType.java, modelservice/src/main/java/com/expedia/adaptivealerting/modelservice/entity/projection/ModelProjection.java, modelservice/src/main/java/com/expedia/adaptivealerting/modelservice/repo/DetectorRepository.java, modelservice/src/main/java/com/expedia/adaptivealerting/modelservice/repo/MetricDetectorMappingRepository.java, modelservice/src/main/java/com/expedia/adaptivealerting/modelservice/repo/ModelRepository.java, modelservice/src/main/sql/build-db.sql, modelservice/src/main/sql/sample-data.sql, modelservice/src/main/sql/stored-procs.sql
This enables us to stores model in db itself instead of S3. 
Changes mapping between a metric <-> model to metric <-> detector -> model
to get all models  for metric hash
` /api/models/search/findByMetricHash?hash=1.71828d68a2938ff1ef96c340f12e2dd6`
=> [Major change][ModelService] Model service schema changes

anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/AnomalyDetectorFactory.java, anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/AnomalyDetectorManager.java, anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/BasicAnomalyDetector.java, anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/BasicAnomalyDetectorFactory.java, anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/aquila/AquilaAnomalyDetectorFactory.java, anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/constant/ConstantThresholdAnomalyDetector.java, anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/constant/ConstantThresholdModel.java, anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/cusum/CusumAnomalyDetector.java, anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/ewma/EwmaAnomalyDetector.java, anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/pewma/PewmaAnomalyDetector.java, anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/rcf/RandomCutForestAnomalyDetectorFactory.java, anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/util/ModelResource.java, anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/util/ModelResources.java, anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/util/ModelServiceConnector.java, kafka/src/main/java/com/expedia/adaptivealerting/kafka/detector/KafkaAnomalyDetectorManager.java, kafka/src/main/resources/config/base.conf, kafka/src/test/scala/com/expedia/adaptivealerting/pipeline/integration/test/ConstantThresholdBasedE2ETestSpec.scala, modelservice/src/main/java/com/expedia/adaptivealerting/modelservice/entity/projection/ModelProjection.java, modelservice/src/main/java/com/expedia/adaptivealerting/modelservice/repo/ModelRepository.java
Just building off #231 just a quick fix for now around getting the `BasicAnomalyDetectorFactory` working for our basic detectors. We will want to clean this up in future.
=> read models from modelservice db instead of S3,  Implement basic detector

modelservice/src/main/java/com/expedia/adaptivealerting/modelservice/repo/MetricRepository.java
added support for finding metrics by its matching key and tag
=> added support for finding metrics

anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/AnomalyDetectorManager.java, kafka/src/main/java/com/expedia/adaptivealerting/kafka/KafkaAnomalyDetectorManager.java, kafka/src/main/resources/config/base.conf, kafka/src/test/java/com.expedia.adaptivealerting.kafka/KafkaAnomalyDetectorManagerTest.java, kafka/src/test/java/com.expedia.adaptivealerting.kafka/KafkaAnomalyDetectorMapperTest.java, kafka/src/test/java/com.expedia.adaptivealerting.kafka/TestObjectMother.java, kafka/src/test/resources/log4j.properties
- Set the default deserialization exception handler to log/continue
- Added unit tests to verify behavior
=> Fixed Kafka deserialization bugs #245 and #253

anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/holtwinters/HoltWintersAnomalyDetector.java, anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/holtwinters/HoltWintersOnlineAlgorithm.java, anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/holtwinters/HoltWintersOnlineComponents.java, anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/holtwinters/HoltWintersParams.java, anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/holtwinters/HoltWintersSimpleTrainingModel.java, anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/holtwinters/HoltWintersTrainingMethod.java, anomdetect/src/test/java/com/expedia/adaptivealerting/anomdetect/holtwinters/HoltWintersAnomalyDetectorTest.java, anomdetect/src/test/java/com/expedia/adaptivealerting/anomdetect/holtwinters/HoltWintersAustouristsTestHelper.java, anomdetect/src/test/java/com/expedia/adaptivealerting/anomdetect/holtwinters/HoltWintersAustouristsTestRow.java, anomdetect/src/test/java/com/expedia/adaptivealerting/anomdetect/holtwinters/HoltWintersParamsTest.java, anomdetect/src/test/java/com/expedia/adaptivealerting/anomdetect/holtwinters/HoltWintersSimpleTrainingModelTest.java, samples/src/main/java/com/expedia/adaptivealerting/samples/CsvTrafficHoltWintersVariants.java, tools/src/main/java/com/expedia/adaptivealerting/tools/pipeline/filter/EvaluatorFilter.java
Uses first two periods to train the components.
=> Added SIMPLE training model to Holt-Winters.

kafka/docker/template/jmxtrans-agent.xml
fixing app name from adaptive-alerting-adaptive-alerting-ad-mapper -> adaptive-alerting-ad-mapper
=> correcting app name for metric prefix

modelservice/docker/jmxtrans-agent.xml
added couple of more HTTP metrics for model service
=> added couple of more HTTP metrics for ms

IntelliJCodeStyle.xml
To use this: Preferences -> Editor -> Code Style -> Scheme -> Click cog dropdown -> Import Scheme... -> IntelliJ IDEA code style XML -> Tick "Current Scheme" to override project settings or give it a unique name like "Adaptive Alerting"
=> Introduce IntelliJCodeStyle.xml for team-agreed code style changes to the IntelliJ defaults.

kafka/src/main/java/com/expedia/adaptivealerting/kafka/KafkaMultiClusterAnomalyToMetricMapper.java
Originally I was using a null timestamp. I'm not sure what that translates
to, but it wouldn't be the timestamp on the underlying MetricData. So in
this commit I grab that timestamp and set it on the ProducerRecord
explicitly.
The hope is that this will align the displayed anomaly series with the
associated metric series.
=> Added anomaly timestamp to records produced by a2m

anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/detectormapper/DetectorMapperCache.java, kafka/docker/template/jmxtrans-agent.xml, kafka/src/main/java/com/expedia/adaptivealerting/kafka/processor/MetricDataTransformer.java
- expiration policy change to expireAfterAccess for eviction of stale mappings
- cache stats collection cleaned up
=> Changes to Guava cache :

modelservice/src/main/java/com/expedia/adaptivealerting/modelservice/repo/impl/DetectorMappingRepositoryImpl.java
bug fix for adding new detector mapping
=> bug fix for adding new detector mapping

modelservice/src/main/java/com/expedia/adaptivealerting/modelservice/repo/impl/DetectorRepositoryImpl.java
added bugfix if UUID is not provided as part of the body while updating a detector
=> added bug fix

anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/util/MetricFrameLoader.java, kafka/src/main/java/com/expedia/adaptivealerting/kafka/TypesafeConfigLoader.java, modelservice/src/main/java/com/expedia/adaptivealerting/modelservice/repo/impl/DetectorRepositoryImpl.java, modelservice/src/main/java/com/expedia/adaptivealerting/modelservice/web/SwaggerConfiguration.java
Bugfix for the vulnerability pointed out by SAST scan.
1) Unreleased Stream
2) Path Manipulation
3) Access Specifier Manipulation
4) Null Dereference
=> Bug fix/sast scan

anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/detect/outlier/algo/ForecastingDetector.java, anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/forecast/point/PointForecaster.java, anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/forecast/point/algo/NaivePointForecaster.java, anomdetect/src/test/java/com/expedia/adaptivealerting/anomdetect/detect/outlier/algo/ForecastingDetectorTest.java, anomdetect/src/test/java/com/expedia/adaptivealerting/anomdetect/forecast/point/algo/NaivePointForecasterTest.java, anomdetect/src/test/java/com/expedia/adaptivealerting/anomdetect/source/factory/LegacyEwmaFactoryTest.java, anomdetect/src/test/java/com/expedia/adaptivealerting/anomdetect/source/factory/LegacyHoltWintersFactoryTest.java, anomdetect/src/test/java/com/expedia/adaptivealerting/anomdetect/source/factory/LegacyPewmaFactoryTest.java
See https://otexts.com/fpp2/simple-methods.html#simple-methods
I have not yet created the factory for this detector, so we can't quite
use it yet. This will require a generic ForecastingDetectorFactory, which
is a little more involved since we want to have per-algo factories for
the individual forecasting algos too. Will take care of this later when I
do the seasonal naive forecaster, since that one we want to actually try
using.
=> Created a naive forecaster per issue #559

docker-compose/README.md, docker-compose/configs/a2m-mapper/a2m-mapper.conf, docker-compose/configs/ad-manager/ad-manager.conf, docker-compose/configs/ad-mapper/ad-mapper.conf, docker-compose/configs/modelservice/application.yml, docker-compose/docker-compose.yml, docker-compose/scripts/populate-es.sh, docker-compose/scripts/start-es.sh, docker-compose/send-sample-metrics.py
Docker-compose configuration for the pipeline along with a demo script to send sample metrics and retrieve anomalies.
=> Add Docker Compose

anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/AlgoParams.java, anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/detect/breakout/algo/EdmxHyperparams.java, anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/detect/outlier/algo/ConstantThresholdParams.java, anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/detect/outlier/algo/CusumParams.java, anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/detect/outlier/algo/IndividualsParams.java, anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/forecast/interval/algo/AdditiveIntervalForecasterParams.java, anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/forecast/interval/algo/ExponentialWelfordIntervalForecasterParams.java, anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/forecast/interval/algo/PowerLawIntervalForecasterParams.java, anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/forecast/point/algo/EwmaPointForecasterParams.java, anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/forecast/point/algo/HoltWintersPointForecasterParams.java, anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/forecast/point/algo/NaivePointForecaster.java, anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/forecast/point/algo/PewmaPointForecasterParams.java, anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/forecast/point/algo/SeasonalNaivePointForecaster.java, anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/forecast/point/algo/SeasonalNaivePointForecasterParams.java, anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/util/AssertUtil.java, anomdetect/src/test/java/com/expedia/adaptivealerting/anomdetect/forecast/point/algo/NaivePointForecasterTest.java, anomdetect/src/test/java/com/expedia/adaptivealerting/anomdetect/forecast/point/algo/SeasonalNaivePointForecasterTest.java
Still need to implement a generic factory for ForecastingDetectors so
we can use both of the new naive forecasters, as well as remove the legacy
factories. I'll take that up in a separate PR.
=> Implemented seasonal naive forecaster per issue #560.

modelservice/src/main/java/com/expedia/adaptivealerting/modelservice/repo/impl/DetectorRepositoryImpl.java, modelservice/src/test/java/com/expedia/adaptivealerting/modelservice/repo/impl/DetectorRepositoryImplTest.java
- Fix xcontent exception on updateDetector API call.
- Sets meta fields on updateDetector API call.
=> Update detector fix

kafka/docker/template/jmxtrans-agent.xml
Bug fix for wrong attribute name
=> Bug fix for wrong attribute name

modelservice/src/main/java/com/expedia/adaptivealerting/modelservice/web/DetectorController.java, modelservice/src/main/java/com/expedia/adaptivealerting/modelservice/web/DetectorMappingController.java, modelservice/src/test/java/com/expedia/adaptivealerting/modelservice/web/DetectorControllerTest.java, modelservice/src/test/java/com/expedia/adaptivealerting/modelservice/web/DetectorMappingControllerTest.java
Return 200 and not 400 when we get an empty list for the specified input
=> Don't throw 400 when we get an empty list for specified input

deployment/terraform/aa-metric-functions/main.tf, deployment/terraform/aa-metric-functions/templates/deployment_yaml.tpl
Reverts ExpediaDotCom/adaptive-alerting#628
=> Revert "move aa-metric-functions input file deployment to load from local pat…"

anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/source/DetectorFactory.java
Adding logs to debug creation of seasonalnaive-detector
=> Adding logs to debug creation of seasonalnaive-detector

anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/source/DetectorFactory.java
Delete some of loggings in detector factory.
=> Delete some of loggings in detector factory.

anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/forecast/point/algo/seasonalnaive/SeasonalBuffer.java
Example logging:
```
2020-01-23 15:38:55 DEBUG SeasonalBuffer:101 - First data point received for Seasonal Buffer.  Buffer has cycleLength=5, interval=10, and starts at timestamp 1563428100 (2019-07-18T05:35:00Z). First metric details: MetricData{metricDefinition=MetricDefinition{key='some-key', tags=TagCollection{kv={}, v=[]}, meta=TagCollection{kv={}, v=[]}}, value=10.0, timestamp=1563428100}
2020-01-23 15:38:55 DEBUG SeasonalBuffer:136 - Updating buffer index 0 with value 10.0
2020-01-23 15:38:55 DEBUG SeasonalBuffer:146 - Current metric timestamp 1563428130 (2019-07-18T05:35:30Z) includes 2 skipped data points since last timestamp 1563428100 (2019-07-18T05:35:00Z)
2020-01-23 15:38:55 DEBUG SeasonalBuffer:136 - Updating buffer index 1 with MISSING PLACEHOLDER value (Infinity) …
```
=> Add some debug logging statements to Seasonal Buffer.

anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/detect/outlier/OutlierDetectorResult.java, anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/detect/outlier/algo/forecasting/ForecastingDetector.java, anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/forecast/point/algo/seasonalnaive/SeasonalBuffer.java, anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/forecast/point/algo/seasonalnaive/SeasonalNaivePointForecaster.java, anomdetect/src/test/java/com/expedia/adaptivealerting/anomdetect/detect/outlier/algo/forecasting/ForecastingDetectorTest.java, anomdetect/src/test/java/com/expedia/adaptivealerting/anomdetect/forecast/point/algo/seasonalnaive/SeasonalNaivePointForecasterTest.java
=> Add warmup to seasonal naive

anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/DetectorInitializationException.java, anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/DetectorManager.java, anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/forecast/point/algo/seasonalnaive/SeasonalBuffer.java, anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/source/data/graphite/GraphiteClient.java, anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/source/data/graphite/GraphiteClientException.java, anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/source/data/initializer/DataInitializer.java, anomdetect/src/main/resources/log4j.properties, anomdetect/src/test/java/com/expedia/adaptivealerting/anomdetect/DetectorManagerTest.java, anomdetect/src/test/resources/log4j.properties, kafka/src/main/java/com/expedia/adaptivealerting/anomdetect/source/data/initializer/DataInitializerFactory.java, kafka/src/main/java/com/expedia/adaptivealerting/kafka/KafkaDetectorManager.java, kafka/src/main/resources/log4j.properties, kafka/src/test-integration/resources/log4j.properties, kafka/src/test/resources/log4j.properties, modelservice/src/main/java/com/expedia/adaptivealerting/modelservice/repo/impl/DetectorRepositoryImpl.java
Added "DetectorUuid" log MDC at key entry points so that UUID of current Detector shows up in logs by default.
=> Ignore DataInitialization failure. Add Detector UUID to MDC.

docker-compose/configs/ad-manager/ad-manager.conf, kafka/src/main/resources/config/base.conf
Adding throttle-gate-likelihood = 0.05 to configs
=> Adding throttle-gate-likelihood = 0.05 to configs

anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/source/data/metrictank/MetrictankSource.java, anomdetect/src/test/java/com/expedia/adaptivealerting/anomdetect/source/data/metrictank/MetrictankSourceTest.java
Fixed metric source log to reflect correct FROM time & updated metric source test for better clarity
=> Fixed log to reflect correct FROM time

metrics/src/main/java/com/expedia/adaptivealerting/metrics/functions/source/graphite/GraphiteQueryInterval.java
Updating member variable visibility in GraphiteQueryInterval
=> Updating member variable visibility in GraphiteQueryInterval

anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/DetectorManager.java
=> Revert "added logs for debugging"

anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/source/data/initializer/DataInitializer.java
Fix to remove whitespaces from the graphite target string
=> Bug fix/whitespaces in graphite target

modelservice/application.yml.sample
We don't have MySQL dependency anymore.
=> config clean up

anomdetect/src/main/resources/log4j.properties
Changed log level to INFO for anomaly detect module
=> Changed log level to INFO for anomaly detect

Makefile, deployment/terraform/main.tf, deployment/terraform/visualizer/main.tf
Reverts ExpediaDotCom/adaptive-alerting#723
Terraform isn't happy that I removed the string interpolations.
=> Revert "Fixed erroneous var defs, and deploy config cleanup"

kafka/src/main/java/com/expedia/adaptivealerting/kafka/visualizer/ElasticSearchClient.java
=> elastic search cluster is slow so bumping up the max timeout to default that is 30 seconds

modelservice/src/main/java/com/expedia/adaptivealerting/modelservice/elasticsearch/ElasticsearchUtil.java, modelservice/src/main/java/com/expedia/adaptivealerting/modelservice/elasticsearch/LegacyElasticSearchClient.java, modelservice/src/main/java/com/expedia/adaptivealerting/modelservice/elasticsearch/LegacyElasticsearchConfig.java, modelservice/src/main/java/com/expedia/adaptivealerting/modelservice/repo/LegacyDetectorRepository.java, modelservice/src/main/java/com/expedia/adaptivealerting/modelservice/repo/impl/DetectorMappingRepositoryImpl.java, modelservice/src/main/java/com/expedia/adaptivealerting/modelservice/repo/impl/LegacyDetectorRepositoryImpl.java, modelservice/src/main/java/com/expedia/adaptivealerting/modelservice/repo/impl/MetricProfileRepositoryImpl.java, modelservice/src/main/java/com/expedia/adaptivealerting/modelservice/util/DetectorIndexCreatorIfNotPresent.java, modelservice/src/main/java/com/expedia/adaptivealerting/modelservice/util/IndexCreatorIfNotPresent.java, modelservice/src/main/java/com/expedia/adaptivealerting/modelservice/util/RequestValidator.java, modelservice/src/main/java/com/expedia/adaptivealerting/modelservice/web/LegacyDetectorController.java, modelservice/src/test/java/com/expedia/adaptivealerting/modelservice/elasticsearch/LegacyElasticsearchConfigTest.java, modelservice/src/test/java/com/expedia/adaptivealerting/modelservice/metricsource/graphite/GraphiteMetricSourceTest.java, modelservice/src/test/java/com/expedia/adaptivealerting/modelservice/repo/impl/DetectorMappingRepositoryImplTest.java, modelservice/src/test/java/com/expedia/adaptivealerting/modelservice/repo/impl/LegacyDetectorRepositoryImplTest.java, modelservice/src/test/java/com/expedia/adaptivealerting/modelservice/repo/impl/MetricProfileRepositoryTest.java, modelservice/src/test/java/com/expedia/adaptivealerting/modelservice/repo/impl/elasticsearch/ElasticsearchUtilTest.java, modelservice/src/test/java/com/expedia/adaptivealerting/modelservice/test/ObjectMother.java, modelservice/src/test/java/com/expedia/adaptivealerting/modelservice/util/DetectorIndexCreatorIfNotPresentTest.java, modelservice/src/test/java/com/expedia/adaptivealerting/modelservice/util/IndexCreatorIfNotPresentTest.java, modelservice/src/test/java/com/expedia/adaptivealerting/modelservice/util/RequestValidatorTest.java, modelservice/src/test/java/com/expedia/adaptivealerting/modelservice/web/CustomExceptionHandlerTest.java, modelservice/src/test/java/com/expedia/adaptivealerting/modelservice/web/LegacyDetectorControllerTest.java
Renamed detector classes and refactored object mother test class. This will be followed up by another PR where we introduce spring data elastic search dependency.
=> Renamed detector classes and refactored object mother test class

modelservice/docker/jmxtrans-agent.xml
Updated object name used to track model service HTTP status codes in jmx config
=> Updated model service jmx config

modelservice/src/main/java/com/expedia/adaptivealerting/modelservice/web/DetectorController.java
Restored v2 request param format for getLastUpdatedDetectors
=> Restored v2 request param format

anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/source/DetectorDocument.java
Updated detector document to reflect new fields
Added comments for deprecated fields
=> Updated detector document to reflect new fields

modelservice/src/main/java/com/expedia/adaptivealerting/modelservice/web/DetectorController.java
Changed updatedDetectorLastUsed method from PUT to POST
=> Changed updatedDetectorLastUsed method

anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/DetectorManager.java, anomdetect/src/test/java/com/expedia/adaptivealerting/anomdetect/DetectorManagerTest.java, modelservice/src/main/java/com/expedia/adaptivealerting/modelservice/service/DetectorServiceImpl.java, modelservice/src/test/java/com/expedia/adaptivealerting/modelservice/service/DetectorServiceImplTest.java
Removed throttling in detector manager and added logging
Added a distinction between detectorLastAccessed and detectorLastUpdated fields
=> Bug fix/detector meta

anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/DetectorManager.java
Added logging to track last accessed time update in ad manager
```
2020-06-03 14:33:36 INFO  DetectorManager:288 () - Updating last used time for a total of 50 invoked detectors
2020-06-03 14:33:36 INFO  DetectorManager:303 () - Updated last used time for a total of 50 invoked detectors
```
=> Added logging to track last accessed time update in ad manager
