ExpediaDotCom/adaptive-alerting

core/src/main/java/com/expedia/adaptivealerting/core/detector/AbstractOutlierDetector.java
core/src/main/java/com/expedia/adaptivealerting/core/detector/ConstantThresholdOutlierDetector.java
core/src/main/java/com/expedia/adaptivealerting/core/detector/EwmaOutlierDetector.java
core/src/main/java/com/expedia/adaptivealerting/core/detector/OutlierDetector.java
core/src/main/java/com/expedia/adaptivealerting/core/detector/OutlierDetectorResult.java
core/src/main/java/com/expedia/adaptivealerting/core/detector/OutlierLevel.java
core/src/main/java/com/expedia/adaptivealerting/core/detector/PewmaOutlierDetector.java
core/src/main/java/com/expedia/adaptivealerting/core/util/MetricPointUtil.java
core/src/test/java/com/expedia/adaptivealerting/core/detector/ConstantThresholdOutlierDetectorTest.java
core/src/test/java/com/expedia/adaptivealerting/core/detector/EwmaOutlierDetectorTest.java
core/src/test/java/com/expedia/adaptivealerting/core/detector/PewmaOutlierDetectorTest.java
kafka/src/main/java/com/expedia/adaptivealerting/kafka/util/DetectorUtil.java
kafka/src/test/java/com/expedia/adaptivealerting/kafka/util/DetectorUtilTest.java
tools/src/main/java/com/expedia/adaptivealerting/tools/pipeline/filter/OutlierDetectorMetricFilter.java
tools/src/main/java/com/expedia/adaptivealerting/tools/pipeline/sink/ChartSink.java

I mistakenly used MetricPoint tags as a mechanism for shuttling outlier
detection results around the data pipeline (tools module). This was a
mistake: MetricPoint tags are for uniquely identifying the metric and not
for carrying metric values around.
Therefore I've updated the OutlierDetector interface so to add a
classify()  method that returns just the classification result, instead of
returning a whole MetricPoint with abused tags. The old classify() method
is still there, but I've renamed it to classifyAndEnrich() and retrofitted
it to use the new classify() method. In later commits I'll correct the
mistake and eventually remove the classifyAndEnrich() method altogether.

Refactored outlier detector in preparation for MetricPoint tags fix.

---

kafka/pom.xml
kafka/src/main/java/com/expedia/adaptivealerting/kafka/detector/ConstantThresholdOutlierDetectorStreamRunnerBuilder.java
kafka/src/main/java/com/expedia/adaptivealerting/kafka/detector/EwmaOutlierDetectorStreamRunnerBuilder.java
kafka/src/main/java/com/expedia/adaptivealerting/kafka/detector/KafkaEwmaOutlierDetector.java
kafka/src/main/java/com/expedia/adaptivealerting/kafka/detector/KafkaPewmaOutlierDetector.java
kafka/src/main/java/com/expedia/adaptivealerting/kafka/detector/PewmaOutlierDetectorStreamRunnerBuilder.java
kafka/src/main/java/com/expedia/adaptivealerting/kafka/router/MetricRouter.java
kafka/src/main/java/com/expedia/adaptivealerting/kafka/router/MetricRouterStreamBuilder.java
kafka/src/main/java/com/expedia/adaptivealerting/kafka/util/StreamRunnerBuilder.java
kafka/src/test/resources/config/base.conf
kafka/src/test/scala/com/expedia/adaptivealerting/pipeline/integration/IntegrationTestSpec.scala
kafka/src/test/scala/com/expedia/adaptivealerting/pipeline/integration/test/ConstantThresholdBasedE2ETestSpec.scala
pom.xml

1. Added a new module 'end2end.test' to hold all the e2e integration tests
2. StreamRunner creation logic from all the existing kstream apps have been moved to separate individual classes inorder to easily integrate with e2e tests.
3. ConstantThresholdBasedE2ETestSpec.scala tests the '(anomalous inputs)->(metric-router)->(constant-threshold-detector)->(output-topic)' E2E pipeline

This includes following changes

---

scripts/publish-to-docker-hub.sh

The script formerly just asked for a password, and it wasn't clear (to me
at least) which password I needed to enter. To avoid mistakes I added a
clarifying prompt.

Clarified the password that `make release` is requesting, per issue #63

---

.travis/deploy.sh
.travis/settings.xml
Makefile
pom.xml

Added 4 plugins
- maven-javadoc-plugin : generates javadoc
-  maven-source-plugin: packages source code
-  maven-gpg-plugin: plugin to sign jar 
- nexus-staging-maven-plugin: plugin to stage jars before pushing to maven
all passwords and secret keys mention in deploy.sh have been configured on travis
I have removed call to deploy.sh for the time being
Will be added again when we want jars to be pushed to maven

scripts and plugins to push jar to maven repo

---

anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/ConstantThresholdAnomalyDetector.java
anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/CusumAnomalyDetector.java
anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/EwmaAnomalyDetector.java
anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/PewmaAnomalyDetector.java
anomdetect/src/test/java/com/expedia/adaptivealerting/anomdetect/ConstantThresholdAnomalyDetectorTest.java
anomdetect/src/test/java/com/expedia/adaptivealerting/anomdetect/CusumAnomalyDetectorTest.java
anomdetect/src/test/java/com/expedia/adaptivealerting/anomdetect/EwmaAnomalyDetectorTest.java
anomdetect/src/test/java/com/expedia/adaptivealerting/anomdetect/PewmaAnomalyDetectorTest.java
anomdetect/src/test/java/com/expedia/adaptivealerting/anomdetect/randomcutforest/MetricPointQueueTest.java
core/src/main/java/com/expedia/adaptivealerting/core/data/Mpoint.java
core/src/main/java/com/expedia/adaptivealerting/core/io/MetricFrameLoader.java
core/src/main/java/com/expedia/adaptivealerting/core/util/MetricPointUtil.java
core/src/test/java/com/expedia/adaptivealerting/core/util/MetricPointUtilTest.java
kafka/src/test/scala/com/expedia/adaptivealerting/pipeline/integration/test/ConstantThresholdBasedE2ETestSpec.scala
tools/src/main/java/com/expedia/adaptivealerting/tools/pipeline/source/MetricFrameMetricSource.java
tools/src/main/java/com/expedia/adaptivealerting/tools/pipeline/source/RandomWalkMetricSource.java
tools/src/main/java/com/expedia/adaptivealerting/tools/pipeline/source/WhiteNoiseMetricSource.java

Some internal integrations require a more incremental approach to
evolving the Haystack MetricPoint representation. Therefore I've updated
the AA Mpoint representation here to use epochTimeInSeconds and a Float
value, instead of using an Instant and a Double value.
I am still interested in using Instant and Double here, but we can have
that conversation after the basic integrations are working.

Align Mpoint more closely with Haystack

---

anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/AnomalyDetector.java
anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/AnomalyDetectorFactory.java
anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/AnomalyDetectorManager.java
anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/ConstantThresholdAnomalyDetector.java
anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/CusumAnomalyDetector.java
anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/EwmaAnomalyDetector.java
anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/PewmaAnomalyDetector.java
anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/randomcutforest/RandomCutForestAnomalyDetector.java
core/src/main/java/com/expedia/adaptivealerting/core/data/MappedMpoint.java
core/src/main/java/com/expedia/adaptivealerting/core/util/ConfigUtil.java
kafka/src/main/java/com/expedia/adaptivealerting/kafka/AbstractKafkaApp.java
kafka/src/main/java/com/expedia/adaptivealerting/kafka/detector/KafkaAnomalyDetectorManager.java
kafka/src/main/java/com/expedia/adaptivealerting/kafka/detector/KafkaConstantThresholdOutlierDetector.java
kafka/src/main/java/com/expedia/adaptivealerting/kafka/detector/KafkaEwmaOutlierDetector.java
kafka/src/main/java/com/expedia/adaptivealerting/kafka/detector/KafkaPewmaOutlierDetector.java
kafka/src/main/java/com/expedia/adaptivealerting/kafka/router/MetricRouter.java
kafka/src/main/java/com/expedia/adaptivealerting/kafka/serde/HaystackMetricTimeStampExtractor.java
kafka/src/main/java/com/expedia/adaptivealerting/kafka/serde/MpointTimestampExtractor.java
kafka/src/main/java/com/expedia/adaptivealerting/kafka/util/AppUtil.java
kafka/src/main/java/com/expedia/adaptivealerting/kafka/util/BaseStreamRunnerBuilder.java
kafka/src/main/java/com/expedia/adaptivealerting/kafka/util/DetectorUtil.java

This commit isolates some key capabilities from the Kafka code:
- Anomaly detector management is no longer tied to Kafka, since we need
management no matter what infrastructure we're using. This is now in the
AnomalyDetectorManager class.
- It adds an AnomalyDetectorFactory class so the manager can produce
detectors on demand.
- It introduces a MappedMpoint class, which is similar to AnomalyResult
except that it's backed my Mpoint instead of Haystack's MetricPoint,
which we're trying to remove. I'm not necessarily attached to the names
"Mpoint" and "MappedMpoint", so we can rename those if desired after we
get rid of the Haystack MetricPoint.
- I changed the AnomalyDetector interface to handle classifications based
on MappedMpoint, but didn't change any of the detectors yet (other than …

Added AnomalyDetectorManager, AnomalyDetectorFactory and Kafka support.

---

anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/AnomalyDetectorMapper.java
anomdetect/src/test/java/com/expedia/adaptivealerting/anomdetect/AnomalyDetectorMapperTest.java
core/src/main/java/com/expedia/adaptivealerting/core/data/MappedMpoint.java
kafka/src/main/java/com/expedia/adaptivealerting/kafka/KafkaConfigProps.java
kafka/src/main/java/com/expedia/adaptivealerting/kafka/detector/KafkaAnomalyDetectorManager.java
kafka/src/main/java/com/expedia/adaptivealerting/kafka/mapper/KafkaAnomalyDetectorMapper.java
kafka/src/main/java/com/expedia/adaptivealerting/kafka/router/MetricRouter.java
kafka/src/main/java/com/expedia/adaptivealerting/kafka/serde/MpointTimestampExtractor.java
kafka/src/main/resources/config/base.conf

MetricRouter is deprecated primarily because the "routing" function is no
longer routing as much as it is message splitting and enrichment. But
there were some other things we needed to take care of anyway. The new
AnomalyDetectorMapper takes care of these:
- Separates the core mapping logic (i.e. the splitting/enrichment) from
the Kafka wrapper
- Consumes Mpoints instead of Haystack MetricPoints
- Produces MappedMpoints instead of Haystack MetricPoints

Created a new AnomalyDetectorMapper, intended to replace MetricRouter.

---

anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/AnomalyDetectorManager.java
core/src/main/java/com/expedia/adaptivealerting/core/util/ReflectionUtil.java
kafka/run-manager.sh
kafka/run-mapper.sh
kafka/src/main/java/com/expedia/adaptivealerting/kafka/detector/KafkaAnomalyDetectorManager.java
pom.xml

Previously, if the metric point had no mapped detector, there would be a
NullPointerException, and it would crash the whole app.
Now we simply skip such metric points, logging a warning.
A couple of improvements too:
- Moved the detector factory configuration out of the Kafka ADManager into
the core ADManager. It's not tied to Kafka so there's no reason for it
to be in the KADManager.
- Moved the ReflectionUtil from the kafka module to the core module. Again
it's not tied to Kafka.

Can now handle missing detectors.

---

anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/AnomalyDetectorMapper.java
anomdetect/src/test/java/com/expedia/adaptivealerting/anomdetect/AnomalyDetectorMapperTest.java
modelservice/src/main/java/com/expedia/adaptivealerting/modelservice/entity/Metric.java
modelservice/src/main/java/com/expedia/adaptivealerting/modelservice/entity/MetricModelMapping.java
modelservice/src/main/java/com/expedia/adaptivealerting/modelservice/entity/Model.java
modelservice/src/main/java/com/expedia/adaptivealerting/modelservice/entity/ModelType.java
modelservice/src/main/sql/build-db.sql
modelservice/src/test/java/com/expedia/adaptivealerting/modelservice/util/JpaConverterJsonTest.java
modelservice/src/test/java/com/expedia/adaptivealerting/modelservice/web/HealthControllerTest.java

- Fixed unit test class names
- Renamed "model_service" db to "aa_model_service" to clarify the app
- Added weak/strong sigma overrides to the model table to support dynamic
adjustments
- Added model types
- Removed on delete/update cascades since Hibernate already manages this
(and I believe expects to manage this)
- Set uuid column to 36 chars (32 alphanumeric + 4 dash)
- Added unique index on metric_model_mapping <metric, model> pairs

Model service enhancements and fixes:

---

anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/AnomalyDetectorFactory.java
anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/constant/ConstantThresholdFactory.java
anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/cusum/CusumFactory.java
kafka/src/main/resources/config/base.conf

The ADManager config expected to see region and bucket params that don't
actually exist. Rather than adding these, I hardcoded the region and
bucket, because we plan to switch over to DB-based model storage very
shortly (in two weeks or so). When we do this, the region and bucket
params go away.

ADManager config bugfix

---

.mvn/wrapper/MavenWrapperDownloader.java
.mvn/wrapper/maven-wrapper.properties
dataservice-athena/src/test/java/com/expedia/adaptivealerting/dataservice/athena/AthenaDataServiceTest.java
kafka/pom.xml
mvnw
mvnw.cmd
notifier/pom.xml
notifier/src/test/java/com/expedia/adaptivealerting/notifier/NotifierApplicationTest.java
pom.xml

Notable change is ensuring more recent scala is used, which implies
Kafka 1.1.1+
Also, a couple tests were never run due to naming convention. This
renames them such that they run.
Fixes #217

Updates build so that it works on JDK 11

---

anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/ewma/EwmaAnomalyDetector.java
anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/source/BasicDetectorSource.java
anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/source/DetectorSource.java
anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/source/ModelServiceDetectorSource.java
anomdetect/src/test/java/com/expedia/adaptivealerting/anomdetect/source/BasicDetectorSourceTest.java

This commit adds a basic detector source that handles both detector UUID
generation and UUID-based detector lookup. We generate UUIDs dynamically
and consistently for a given MetricDefinition. Once we have a detector
UUID, we use that to create/retrieve an in-memory EWMA detector.
The AD Mapper will use UUID generation, and the AD Manager will use UUID-
based detector lookup. This will follow in a subsequent commit.
This allows us to map EWMA detectors to any incoming metric without any
user intervention, and without going to the model service.

Added basic detector source in preparation for Haystack metrics.

---

anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/DetectorLookup.java
anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/source/DefaultDetectorSource.java
deployment/terraform/ad-manager/templates/ad-manager_conf.tpl
deployment/terraform/ad-mapper/templates/ad-mapper_conf.tpl
kafka/src/main/resources/config/base.conf

Previously the detector registry was defined in multiple config files.
It's the same registry across all apps, so there's no need for that.
Moreover, there's not really any need for this to be config files, since
the detector registry is wholly dependent on the built-in detectors
available. So I just implemented a DetectorLookup class. When people
create new detectors they need to create an entry in this class.

DRY up detector registry

---

anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/ewma/EwmaAnomalyDetector.java
anomdetect/src/test/java/com/expedia/adaptivealerting/anomdetect/AnomalyToMetricMapperTest.java
anomdetect/src/test/java/com/expedia/adaptivealerting/anomdetect/ewma/EwmaAnomalyDetectorTest.java
anomdetect/src/test/java/com/expedia/adaptivealerting/anomdetect/ewma/EwmaTestRow.java
core/src/main/java/com/expedia/adaptivealerting/core/util/MetricUtil.java
kafka/src/main/java/com/expedia/adaptivealerting/kafka/KafkaMultiClusterAnomalyToMetricMapper.java
kafka/src/test/java/com.expedia.adaptivealerting.kafka/KafkaMultiClusterAnomalyToMetricMapperTest.java
kafka/src/test/java/com.expedia.adaptivealerting.kafka/util/TestObjectMother.java

In production we see metrics with null tag values, for whatever reason.
Metricstank and Metrics 2.0 don't support this, so currently such metrics
generate IllegalArgumentExceptions and the mapper gets stuck on them.
This commit catches the IllegalArgumentException and responds by returning
null for offending metrics.

mc-a2m-mapper must handle tags with null values

---

anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/AbstractAnomalyDetector.java
anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/DetectorParams.java
anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/constant/ConstantThresholdAnomalyDetector.java
anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/constant/ConstantThresholdParams.java
anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/cusum/CusumAnomalyDetector.java
anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/cusum/CusumParams.java
anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/ewma/EwmaAnomalyDetector.java
anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/ewma/EwmaParams.java
anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/holtwinters/HoltWintersAnomalyDetector.java
anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/holtwinters/HoltWintersParams.java
anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/individuals/IndividualsControlChartAnomalyDetector.java
anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/individuals/IndividualsControlChartParams.java
anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/pewma/PewmaAnomalyDetector.java
anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/pewma/PewmaParams.java
anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/source/DefaultDetectorSource.java
anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/source/TempHaystackAwareDetectorSource.java
anomdetect/src/test/java/com/expedia/adaptivealerting/anomdetect/constant/ConstantThresholdAnomalyDetectorTest.java
anomdetect/src/test/java/com/expedia/adaptivealerting/anomdetect/cusum/CusumAnomalyDetectorTest.java
anomdetect/src/test/java/com/expedia/adaptivealerting/anomdetect/ewma/EwmaAnomalyDetectorTest.java
anomdetect/src/test/java/com/expedia/adaptivealerting/anomdetect/holtwinters/HoltWintersAnomalyDetectorTest.java
anomdetect/src/test/java/com/expedia/adaptivealerting/anomdetect/individuals/IndividualsChartAnomalyDetectorTest.java
anomdetect/src/test/java/com/expedia/adaptivealerting/anomdetect/pewma/PewmaAnomalyDetectorTest.java
samples/src/main/java/com/expedia/adaptivealerting/samples/CsvTrafficHoltWintersVariants.java
samples/src/main/java/com/expedia/adaptivealerting/samples/CsvTrafficPewmaVariants.java
samples/src/main/java/com/expedia/adaptivealerting/samples/Sample001.java

The original detector initialization process was somewhat byzantine, with
initialization sometimes happening in constructors and sometimes in the
init() method. This led to a bug with Holt-Winters because we were
initializing with invalid params, and then calling params.validate() and
failing. (This commit fixes that issue.)
The AbstractAnomalyDetector base class is simpler now, and the subclasses
based on that are simpler too. They don't have to implement so many
abstract methods.
Also we were storing weak/strong sigmas in both the detector directly and
in the params object. The detector fields didn't do anything, and this was
leading to confusion about which ones do something and why the values are
different. I removed the detector fields since weak/strong sigmas are in
fact detector …

Refactoring to simplify detector initialization

---

anomdetect/pom.xml
anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/source/DefaultDetectorSource.java
anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/util/DetectorResource.java
anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/util/DetectorResources.java
anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/util/ModelResource.java
anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/util/ModelResources.java
anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/util/ModelServiceConnector.java
anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/util/ModelTypeResource.java
anomdetect/src/test/java/com/expedia/adaptivealerting/anomdetect/source/DefaultDetectorSourceTest.java
anomdetect/src/test/java/com/expedia/adaptivealerting/anomdetect/util/ModelServiceConnectorTest.java
modelservice/src/main/java/com/expedia/adaptivealerting/modelservice/repo/MetricRepository.java

We were having some trouble with the Spring HATEOAS-based Jackson module,
as the serializer doesn't have a noarg constructor, and the unit tests
were failing when trying to create a serializer. So this commit replaces
that with custom resource objects, which is nice anyway because it allows
us to avoid pulling in a bunch of Spring dependencies just for a few
resources.

Replaced Spring HATEOAS with custom code

---

deployment/terraform/main.tf
deployment/terraform/modelservice/main.tf
deployment/terraform/modelservice/templates/application_yaml.tpl
deployment/terraform/modelservice/variables.tf
modelservice/application.yml.sample
modelservice/src/main/java/com/expedia/adaptivealerting/modelservice/dto/percolator/PercolatorDetectorMapping.java
modelservice/src/main/java/com/expedia/adaptivealerting/modelservice/elasticsearch/ElasticSearchProperties.java
modelservice/src/main/java/com/expedia/adaptivealerting/modelservice/util/DetectorIndexCreatorIfNotPresent.java
modelservice/src/test/java/com/expedia/adaptivealerting/modelservice/util/DetectorIndexCreatorIfNotPresentTest.java

Adds new class to pre-create index mappings for detectors elasticsearch index if it does not exist.
This is required to spin up a working docker-compose instance of this project from scratch.
This adds additional index name and doctype parameters to the application.yml for the modelservice. If the new parameters are not present the index creation process is not started to remain compatible with existing configs.

Pre-create index mapping for detector index

---

modelservice/src/main/java/com/expedia/adaptivealerting/modelservice/exception/CustomExceptionHandler.java
modelservice/src/main/java/com/expedia/adaptivealerting/modelservice/web/AnomalyController.java
modelservice/src/main/java/com/expedia/adaptivealerting/modelservice/web/DetectorController.java
modelservice/src/test/java/com/expedia/adaptivealerting/modelservice/web/CustomExceptionHandlerTest.java
modelservice/src/test/java/com/expedia/adaptivealerting/modelservice/web/DetectorControllerTest.java

Make CustomExceptionHandler.handleRecordNotFound() public (was 'protected' previously which meant it wasn't handling RecordNotFoundException exceptions at all).
Added unit tests for CustomExceptionHandler

Fix CustomExceptionHandler.handleRecordNotFound()

---

kafka/src/main/resources/log4j.properties

Changing the log level to DEBUG for testing purpose. We will change it back to INFO once done we are done with the testing.

Changing log level to debug for testing purpose

---

anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/source/data/graphite/GraphiteClient.java
anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/source/data/graphite/GraphiteClientException.java
anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/source/data/graphite/GraphiteResult.java
anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/source/data/graphite/GraphiteSource.java
anomdetect/src/test/java/com/expedia/adaptivealerting/anomdetect/source/data/graphite/GraphiteClientTest.java
anomdetect/src/test/java/com/expedia/adaptivealerting/anomdetect/source/data/graphite/GraphiteSourceTest.java
kafka/src/main/java/com/expedia/adaptivealerting/anomdetect/source/data/initializer/DataInitializerFactory.java

Renamed metrictank to graphite to maintain the consistency.
`x-org-id is a mandatory header for metric tank. In future, we would like to make it configurable as the only difference between graphite client and metric tank client is x-org-id header.`

Renamed metrictank to graphite

---

deployment/terraform/aa-metric-functions/templates/aa-metric-functions_conf.tpl
kafka/src/main/resources/config/base.conf
metrics/src/main/java/com/expedia/adaptivealerting/metrics/functions/service/graphite/GraphiteQueryService.java
metrics/src/main/java/com/expedia/adaptivealerting/metrics/functions/source/graphite/ConstructSourceURI.java
metrics/src/main/java/com/expedia/adaptivealerting/metrics/functions/source/graphite/GraphiteQueryInterval.java
metrics/src/test/java/com/expedia/adaptivealerting/metrics/functions/service/graphite/GraphiteQueryServiceTest.java
metrics/src/test/java/com/expedia/adaptivealerting/metrics/functions/source/graphite/ConstructSourceURITest.java
metrics/src/test/resources/config/base.conf

Creating interval for querying graphite based on current timestamp.
When querying Graphite the FROM and UNTIL date settings must be specified precisely in order to return consistent results.
For Aggregator use the following:
FROM: (START_OF_PREVIOUS_INTERVAL - 1s)
UNTIL: START_OF_CURRENT_INTERVAL
where:
START_OF_CURRENT_INTERVAL = (<metric's timestamp> / INTERVAL) * INTERVAL
START_OF_PREVIOUS_INTERVAL = START_OF_CURRENT_INTERVAL - INTERVAL

Creating interval for querying graphite based on current timestamp

---

anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/DetectorManager.java
anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/source/DefaultDetectorSource.java
anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/source/DetectorClient.java
anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/source/DetectorSource.java
anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/source/data/initializer/DataInitializer.java
anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/util/MetricUtil.java
anomdetect/src/test/java/com/expedia/adaptivealerting/anomdetect/DetectorManagerTest.java
anomdetect/src/test/java/com/expedia/adaptivealerting/anomdetect/source/data/initializer/DataInitializerTest.java
anomdetect/src/test/java/com/expedia/adaptivealerting/anomdetect/util/MetricUtilTest.java

Use tags mentioned in detector mappings to query graphite when function tag is not available as part of the incoming metric. This is required for ELB 2xx metrics as it doesn't need to go via an aggregator.
`Use seriesByTag('tags') in case function tag is not there. Else use the function tag value to query graphite.`

Added change to querty graphite directly via tags

---

docker-compose/docker-compose.yml

Upgraded elastic search version in docker compose from 6.5 to 6.7

Upgraded elastic search version in docker compose

---

anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/DetectorManager.java
anomdetect/src/test/java/com/expedia/adaptivealerting/anomdetect/DetectorManagerTest.java

Use LinkedHashSet for detectorsLastUsedTimeToBeUpdatedSet instead of HashSet to maintain the order in which UUIDs are added

Use LinkedHashSet instead of HashSet to maintain the order

---

anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/DetectorManager.java

Use ConcurrentLinkedQueue to maintain the UUIDs for which `lastAccessedTime` needs to be updated and convert it into a HashSet before calling the elastic search to prevent duplicate calls.
Unique Detector UUIDs
```
2020-06-04 12:38:09 INFO  DetectorManager:296 () - Detectors last used time queue size 50
2020-06-04 12:38:09 INFO  DetectorManager:299 () - Updating last used time for a total of 50 invoked detectors
2020-06-04 12:38:09 INFO  DetectorManager:325 () - Updated last used time for a total of 50 invoked detectors
```
Duplicate Detector UUIDs
```
2020-06-04 12:38:09 INFO  DetectorManager:296 () - Detectors last used time queue size 4
2020-06-04 12:38:09 INFO  DetectorManager:299 () - Updating last used time for a total of 1 invoked detectors
2020-06-04 12:38:09 INFO …
```

Bug fix/concurrent modification exception

---

anomdetect/src/main/java/com/expedia/adaptivealerting/anomdetect/DetectorManager.java
anomdetect/src/test/java/com/expedia/adaptivealerting/anomdetect/DetectorManagerTest.java

Updated detectors last time used log statement:
**Unique detectors:**
```
2020-06-05 10:29:40 INFO  DetectorManager:310 () - Updated detectors last time used: detectorsUpdated=50, uniqueDetectorsInvoked=50 , totalDetectorsInvoked=50
```
**Duplicate detectors:**
```
2020-06-05 10:31:26 INFO  DetectorManager:309 () - Updated detectors last time used: detectorsUpdated=1, uniqueDetectorsInvoked=1 , totalDetectorsInvoked=4
```
**Invalid detectors:**
```
2020-06-05 10:31:13 INFO  DetectorManager:309 () - Updated detectors last time used: detectorsUpdated=1, uniqueDetectorsInvoked=2 , totalDetectorsInvoked=2
```

Changed log statement

---

modelservice/src/main/java/com/expedia/adaptivealerting/modelservice/web/DetectorMappingController.java

Updated delete mappings by detector uuid endpoint since `/search/findByDetector` was a bit confusing and meant one could use it for search.

Updated delete mappings by detector uuid endpoint

---

modelservice/src/main/java/com/expedia/adaptivealerting/modelservice/entity/Detector.java
modelservice/src/main/java/com/expedia/adaptivealerting/modelservice/repo/DetectorRepository.java
modelservice/src/main/java/com/expedia/adaptivealerting/modelservice/service/DetectorService.java
modelservice/src/main/java/com/expedia/adaptivealerting/modelservice/service/DetectorServiceImpl.java
modelservice/src/main/java/com/expedia/adaptivealerting/modelservice/util/DetectorDataUtil.java
modelservice/src/main/java/com/expedia/adaptivealerting/modelservice/util/RequestValidator.java
modelservice/src/main/java/com/expedia/adaptivealerting/modelservice/web/DetectorController.java
modelservice/src/test/java/com/expedia/adaptivealerting/modelservice/service/DetectorServiceImplTest.java
modelservice/src/test/java/com/expedia/adaptivealerting/modelservice/test/ObjectMother.java
modelservice/src/test/java/com/expedia/adaptivealerting/modelservice/web/DetectorControllerTest.java

* Adding scheduler information to `detectorConfig.trainingMetaData` inside detector document
* Creating API endpoint `getNextDetectorsToTrain` to get a list of detectors to be trained next
* Creating API endpoint `updateDetectorTrainingTime` to update training run timestamps upon training initiated.
* Modifying update detector endpoint to prevent overriding/loosing `trainingMetaData` if not passed in `PUT` payload

Combining AA scheduler data to modelService detector document

---

modelservice/src/main/java/com/expedia/adaptivealerting/modelservice/service/DetectorService.java
modelservice/src/main/java/com/expedia/adaptivealerting/modelservice/service/DetectorServiceImpl.java
modelservice/src/main/java/com/expedia/adaptivealerting/modelservice/web/DetectorController.java
modelservice/src/test/java/com/expedia/adaptivealerting/modelservice/service/DetectorServiceImplTest.java
modelservice/src/test/java/com/expedia/adaptivealerting/modelservice/web/DetectorControllerTest.java

Adding a timestamp parameter to `getDetectorsToTrain` endpoint, so it can retrieve a list of detectors to be trained at specific timestamp value.

adding timestamp parameter to getDetectorsToTrain endpoint
